---
###############################################################################
# Finder                                                                      #
###############################################################################

# Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
# defaults write com.apple.finder QuitMenuItem -bool true
# 
# this seems fucking pointless

- name: "Finder: disable window animations and Get Info animations"
  state:
    defaults:
      # defaults write com.apple.finder DisableAllAnimations -bool true
      key: com.apple.finder:DisableAllAnimations
      set: true
  when: osx_finder_disable_animations

- name: Set home as the default location for new Finder windows
  # For other paths, use `PfLo` and `file:///full/path/here/`
  state:
    defaults:
    # defaults write com.apple.finder NewWindowTarget -string "PfHm"
    - key: com.apple.finder:NewWindowTarget
      set: PfHm
    # defaults write com.apple.finder NewWindowTargetPath -string "file://localhost${HOME}/"
    - key: com.apple.finder:NewWindowTargetPath
      set: "file://localhost{{ lookup('env', 'HOME') }}/"
  when: osx_finder_default_to_home

- name: don't show icons for hard drives, servers, and removable media on the desktop
  state:
    defaults:
    # defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    - key: com.apple.finder:ShowExternalHardDrivesOnDesktop
      set: false
    # defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    - key: com.apple.finder:ShowHardDrivesOnDesktop
      set: false
    # defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    - key: com.apple.finder:ShowMountedServersOnDesktop
      set: false
    # defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
    - key: com.apple.finder:ShowRemovableMediaOnDesktop
      set: false
  notify:
  - restart Finder
  when: osx_finder_no_drives_on_desktop

- name: "Finder: show hidden files by default"
  state:
    defaults:
      # defaults write com.apple.finder AppleShowAllFiles -bool true
      key: com.apple.finder:AppleShowAllFiles
      set: true
  when: osx_finder_show_hidden_files

- name: "Finder: show all filename extensions"
  state:
    defaults:
      # defaults write NSGlobalDomain AppleShowAllExtensions -bool true
      key: NSGlobalDomain:AppleShowAllExtensions
      set: true
  when: osx_finder_show_file_extensions

- name: "Finder: show status bar"
  state:
    defaults:
      # defaults write com.apple.finder ShowStatusBar -bool true
      key: com.apple.finder:ShowStatusBar
      set: true
  when: osx_finder_show_status_bar

- name: "Finder: show path bar"
  state:
    defaults:
      # defaults write com.apple.finder ShowPathbar -bool true
      key: com.apple.finder:ShowPathbar
      set: true
  when: osx_finder_show_path_bar

- name: "Finder: allow text selection in Quick Look"
  state:
    defaults:
      # defaults write com.apple.finder QLEnableTextSelection -bool true
      key: com.apple.finder:QLEnableTextSelection
      set: true
  when: osx_finder_selection_in_quick_look

- name: Display full POSIX path as Finder window title
  state:
    defaults:
      # defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
      key: com.apple.finder:_FXShowPosixPathInTitle
      set: true
  when: osx_finder_posix_path_as_title

- name: When performing a search, search the current folder by default
  state:
    defaults:
      # defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
      key: com.apple.finder:FXDefaultSearchScope
      set: SCcf
  when: osx_finder_default_search_to_current_folder

- name: Disable the warning when changing a file extension
  state:
    defaults:
      # defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
      key: com.apple.finder:FXEnableExtensionChangeWarning
      set: false
  when: osx_finder_disable_change_extension_warning

- name: Enable spring loading for directories
  state:
    defaults:
      # defaults write NSGlobalDomain com.apple.springing.enabled -bool true
      key: NSGlobalDomain:com.apple.springing.enabled
      set: true
  when: osx_finder_spring_load_dirs

- name: Set spring loading delay for directories
  state:
    defaults:
      # defaults write NSGlobalDomain com.apple.springing.delay -float 0.5
      key: NSGlobalDomain:com.apple.springing.delay
      set: "{{ osx_finder_spring_load_delay|float }}"
  when: osx_finder_spring_load_delay is defined

- name: Avoid creating .DS_Store files on network volumes
  state:
    defaults:
      # defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
      key: com.apple.desktopservices:DSDontWriteNetworkStores
      set: true
  when: osx_finder_no_ds_store_on_network_volumes

# Disable disk image verification
# defaults write com.apple.frameworks.diskimages skip-verify -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
#
# TODO: why?

# Automatically open a new Finder window when a volume is mounted
# defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
# defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
# defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
#
# not sure i like this

- name: Show item info near icons on the desktop and in other icon views
  # WARNING:  looks like this has the unintended effect of replacing floats
  #           that are whole numbers with integers :(
  #
  #           so far seems like finder is ok with it, but might cause issues
  #           with other stuff.
  state:
    defaults:
    # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
    # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
    # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
    - key: "com.apple.finder:{{ item }}:IconViewSettings:showItemInfo"
      set: true
  with_items:
  - DesktopViewSettings
  - FK_StandardViewSettings
  - StandardViewSettings
  notify:
  - restart Finder
  when: osx_finder_info_in_icon_views

- name: Show item info to the right of the icons on the desktop
  state:
    defaults:
      # /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist
      key: com.apple.finder:DesktopViewSettings:IconViewSettings:labelOnBottom
      set: false
  notify:
  - restart Finder
  when: osx_finder_desktop_info_on_right

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  state:
    defaults:
      # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
      key: "com.apple.finder:{{ item }}:IconViewSettings:arrangeBy"
      # default was 'none'
      set: grid
  with_items:
  - DesktopViewSettings
  - FK_StandardViewSettings
  - StandardViewSettings
  notify:
  - restart Finder
  when: osx_finder_icon_snap_to_grid

- name: set grid spacing for icons on the desktop and in other icon views
  state:
    defaults:
      # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
      key: "com.apple.finder:{{ item }}:IconViewSettings:gridSpacing"
      # default: 54
      # mths: 100
      set: "{{ osx_finder_icon_spacing|int }}"
  with_items:
  - DesktopViewSettings
  - FK_StandardViewSettings
  - StandardViewSettings
  notify:
  - restart Finder
  when: osx_finder_icon_spacing is defined

- name: set the size of icons on the desktop and in other icon views
  state:
    defaults:
      # /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
      # /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
      key: "com.apple.finder:{{ item }}:IconViewSettings:iconSize"
      # default: 64
      # mths: 80
      set: "{{ osx_finder_icon_size|int }}"
  with_items:
  - DesktopViewSettings
  - FK_StandardViewSettings
  - StandardViewSettings
  notify:
  - restart Finder
  when: osx_finder_icon_size is defined

- name: Use list view in all Finder windows by default
  state:
    defaults:
      # defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
      key: com.apple.finder:FXPreferredViewStyle
      # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
      set: Nlsv
  notify:
  - restart Finder
  when: osx_finder_list_view_default

- name: Disable the warning before emptying the Trash
  state:
    defaults:
      # defaults write com.apple.finder WarnOnEmptyTrash -bool false
      key: com.apple.finder:WarnOnEmptyTrash
      set: false
  when: osx_finder_diable_empty_trash_warning

# Empty Trash securely by default
# defaults write com.apple.finder EmptyTrashSecurely -bool true
# 
# this can really slow things down, especially when trying to knock
# out large media files to make emergency space

# # Enable AirDrop over Ethernet and on unsupported Macs running Lion
# defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true
#
# not sure i care

# # Enable the MacBook Air SuperDrive on any Mac
# sudo nvram boot-args="mbasd=1"
#
# don't think i care

# TODO: shouldn't run every time if possible
- name: Show the ~/Library folder
  command: chflags nohidden ~/Library
  when: osx_finder_show_user_library

# Remove Dropbox’s green checkmark icons in Finder
# file=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns
# [ -e "${file}" ] && mv -f "${file}" "${file}.bak"
# 
# i like em!

# TODO: ugh... deep comparisons needed to deal with the 0/1/true/false shit
- name: set the File Info panes to expand
  state:
    defaults:
      # “General”, “Open with”, and “Sharing & Permissions”
      #
      #     defaults write com.apple.finder FXInfoPanesExpanded -dict \
      #       General -bool true \
      #       OpenWith -bool true \
      #       Privileges -bool true
      #
      key: com.apple.finder:FXInfoPanesExpanded
      set:
        Comments: false
        General: true
        MetaData: false
        Name: false
        OpenWith: true
        Preview: false
        Privileges: true
  notify:
  - restart Finder
  when: osx_finder_expand_file_info