---
###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

- name: Trackpad - enable tap to click for this user and for the login screen
  state:
    defaults:
      # 
      #     defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
      #
      - key: com.apple.driver.AppleBluetoothMultitouch.trackpad:Clicking
        set: true
      #
      #     defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
      # 
      - key: NSGlobalDomain:com.apple.mouse.tapBehavior
        set: 1
        options:
          current_host: true
      # 
      #     defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
      #
      - key: NSGlobalDomain:com.apple.mouse.tapBehavior
        set: 1
  notify:
  - require logout/login
  when: osx_trackpad_click_to_tap

# Trackpad: map bottom right corner to right-click
# 
#     defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
#     defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
#     defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
#     defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# Disable “natural” (Lion-style) scrolling
# 
#     defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

- name: Increase sound quality for Bluetooth headphones/headsets
  state:
    defaults:
    # 
    #     defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
    #
      key: com.apple.BluetoothAudioAgent:Apple Bitpool Min (editable)
      set: 40
  when: osx_better_bluetooth_audio

- name: Enable full keyboard access for all controls
  # (e.g. enable Tab in modal dialogs)
  state:
    defaults:
      # 
      #     defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
      # 
      key: NSGlobalDomain:AppleKeyboardUIMode
      set: 3
  when: osx_full_keyboard_access

# Use scroll gesture with the Ctrl (^) modifier key to zoom
# defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
# defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

# Follow the keyboard focus while zoomed in
# defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Disable press-and-hold for keys in favor of key repeat
# defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
# defaults write NSGlobalDomain KeyRepeat -int 0

- name: Set languages
  # Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
  # `Inches`, `en_GB` with `en_US`, and `true` with `false`.
  state:
    defaults:
      #
      #     defaults write NSGlobalDomain AppleLanguages -array "en" "nl"
      # 
      key: NSGlobalDomain:AppleLanguages
      set: "{{ osx_languages }}"
  when: osx_languages is defined

- name: set locale
  #
  #     defaults write NSGlobalDomain AppleLocale -string "en_US@currency=USD"
  #
  state:
    defaults:
      key: NSGlobalDomain:AppleLocale 
      set: "{{ osx_locale }}"
  when: osx_locale is defined

- name: set units
  state:
    defaults:
    # 
    #     defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
    # 
      key: NSGlobalDomain:AppleMeasurementUnits
      set: "{{ osx_units }}"
  when: osx_units is defined

- name: set metric
  state:
    defaults:
    # 
    #     defaults write NSGlobalDomain AppleMetricUnits -bool true
    # 
      key: NSGlobalDomain:AppleMetricUnits
      set: "{{ osx_metric }}"
  when: osx_metric is defined

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
# sudo systemsetup -settimezone "Europe/Brussels" > /dev/null
# 
# think i want this to be set automatically

# Disable auto-correct
# defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
# 
# not sure if i want this... my spelling sucks

- name: Stop iTunes from responding to the keyboard media keys
  state:
    launchd:
      # 
      #     launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null
      #
      key:
      - /System/Library/LaunchAgents/com.apple.rcd.plist
      - Disabled
      set: true
  sudo: true
  # TODO: this fails if the item is not there?
  ignore_errors: true
  when: osx_itunes_ignore_media_keys

- name: include simplified chinese pinyin input
  state:
    defaults:
      - key: com.apple.HIToolbox:AppleEnabledInputSources
        array_contains:
          Bundle ID: com.apple.inputmethod.SCIM
          Input Mode: com.apple.inputmethod.SCIM.ITABC
          InputSourceKind: Input Mode
      - key: com.apple.HIToolbox:AppleEnabledInputSources
        array_contains:
          Bundle ID: com.apple.inputmethod.SCIM
          InputSourceKind: Keyboard Input Method
  when: osx_simplified_pinyin
