---
# ###############################################################################
# # Mail                                                                        #
# ###############################################################################

- name: send animations in Mail.app
  when: osx_mail_send_animations is defined
  state:
    defaults:
      # defaults write com.apple.mail DisableSendAnimations -bool true
      key: com.apple.mail:DisableSendAnimations
      set: "{{ not osx_mail_send_animations }}"
      type: bool

- name: reply animations in Mail.app
  when: osx_mail_reply_animations is defined
  state:
    defaults:
      # defaults write com.apple.mail DisableReplyAnimations -bool true
      key: com.apple.mail:DisableReplyAnimations
      set: "{{ not osx_mail_send_animations }}"
      type: bool

- name: include name when copying emails addresses in Mail.app
  when: osx_mail_include_name_when_copying_email_addresses is defined
  state:
    defaults:
      # defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false
      key: com.apple.mail:AddressesIncludeNameOnPasteboard
      set: "{{ osx_mail_include_name_when_copying_email_addresses }}"
      type: bool

# - name: Mail.app send shortcut
#   when: osx_mail_send_shortcut is defined
#   debug:
#     msg: "{{ osx_mail_send_shortcut|osx_hotkey }}"

# TODO this *may* have been what broke the system prefs keyboard pane
# (requiring me to re-install OSX)
#
# - name: keyboard shortcut ⌘ + Enter to send an email in Mail.app
#   when: osx_mail_cmd_enter_send is defined
#   state:
#     defaults:
#       # defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"
#       key: com.apple.mail:NSUserKeyEquivalents:Send
#       set: '@\\U21a9'
#       create: true
#       unset_when: "{{ osx_mail_cmd_enter_send is sameas false }}"

- name: Display in threaded mode in Mail.app
  when: osx_mail_threaded_mode is defined
  state:
    defaults:
      # defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
      key: com.apple.mail:DraftsViewerAttributes:DisplayInThreadedMode
      set: "yes"
      type: string
      unset_when: "{{ osx_mail_threaded_mode is sameas false }}"

- name: sort descending in Mail.app
  when: osx_mail_sort_descending is defined
  state:
    defaults:
      # defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
      key: com.apple.mail:DraftsViewerAttributes:SortedDescending
      set: "yes"
      type: string
      unset_when: "{{ osx_mail_sort_descending is sameas false }}"

- name: sort order in Mail.app
  when: osx_mail_sort_order is defined
  state:
    defaults:
      # defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"
      key: com.apple.mail:DraftsViewerAttributes:SortOrder
      set: "{{ osx_mail_sort_order }}"
      unset_when_false: true

- name: Disable inline attachments (just show the icons) in Mail.app
  when: osx_mail_disable_inline_attachments is defined
  state:
    # defaults write com.apple.mail DisableInlineAttachmentViewing -bool true
    key: com.apple.mail:DisableInlineAttachmentViewing
    set: "{{ osx_mail_disable_inline_attachments }}"
    type: bool
    unset_when_false: true

- name: spell checking behavior in Mail.app
  when: osx_mail_spell_checking_behavior is defined
  state:
    defaults:
      # defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"
      key: com.apple.mail:SpellCheckingBehavior
      set: "{{ osx_mail_spell_checking_behavior }}"
      unset_when_false: true
