---
###############################################################################
# Safari & WebKit                                                             #
###############################################################################

- name: universal search (from url bar?) in Safari 
  state:
    defaults:
      # defaults write com.apple.Safari UniversalSearchEnabled -bool false
      key: com.apple.Safari:UniversalSearchEnabled
      set: "{{ osx_safari_universal_search }}"
      type: bool
  when: osx_safari_universal_search is defined

- name: search suggestions in safari
  state:
    defaults:
      # defaults write com.apple.Safari SuppressSearchSuggestions -bool true
      key: com.apple.Safari:SuppressSearchSuggestions
      set: "{{ not osx_safari_search_suggestions }}"
      type: bool
  when: osx_safari_search_suggestions is defined

- name: Press Tab to highlight each item on a web page
  state:
    defaults:
      # defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
      - key: com.apple.Safari:WebKitTabToLinksPreferenceKey
        set: "{{ osx_safari_tab_highlight_items }}"
        type: bool
      # defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true
      - key: com.apple.Safari:com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks
        set: "{{ osx_safari_tab_highlight_items }}"
        type: bool
  when: osx_safari_tab_highlight_items is defined

- name: Show the full URL in the address bar
  state:
    defaults:
      key: com.apple.Safari:ShowFullURLInSmartSearchField
      set: "{{ osx_safari_full_url_in_address_bar }}"
      type: bool
  when: osx_safari_full_url_in_address_bar is defined

- name: Set Safari’s home page to `about:blank` for faster loading
  state:
    defaults:
      key: com.apple.Safari:HomePage
      set: "{{ osx_safari_home_page }}"
  when: osx_safari_home_page is defined

- name: open 'safe' files automatically after downloading in Safari
  state:
    defaults:
      key: com.apple.Safari:AutoOpenSafeDownloads
      set: "{{ osx_safari_auto_open_safe_files }}"
      type: bool
  when: osx_safari_auto_open_safe_files is defined

- name: backspace key to go to the previous page in history
  state:
    defaults:
      key: com.apple.Safari:com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled
      set: "{{ osx_safari_backspace_back }}"
      type: bool
  when: osx_safari_backspace_back is defined

- name: show Safari’s favorite (bookmarks) bar
  state:
    defaults:
      key: com.apple.Safari:ShowFavoritesBar
      set: "{{ osx_safari_show_favs_bar }}"
      type: bool
  when: osx_safari_show_favs_bar is defined

- name: show Safari’s sidebar in Top Sites
  when: osx_safari_sidebar_in_top_sites is defined
  state:
    defaults:
      # defaults write com.apple.Safari ShowSidebarInTopSites -bool false
      key: com.apple.Safari:ShowSidebarInTopSites
      set: "{{ osx_safari_sidebar_in_top_sites }}"
      type: bool

- name: Disable Safari’s thumbnail cache for History and Top Sites
  state:
    defaults:
      key: com.apple.Safari:DebugSnapshotsUpdatePolicy
      set: 2
      # seems to come unset, so unset when false
      unset_when_false: true
  when: osx_safari_disable_hist_top_sites_thumbs is defined

- name: Enable Safari’s debug menu
  state:
    defaults:
      key: com.apple.Safari:IncludeInternalDebugMenu
      set: "{{ osx_safari_enable_debug_menu }}"
      type: bool
  when: osx_safari_enable_debug_menu is defined

- name: match only at word starts in Safari’s search banners
  when: osx_safari_find_match_word_starts_only is defined
  state:
    defaults:
      # defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false
      key: com.apple.Safari:FindOnPageMatchesWordStartsOnly
      set: "{{ osx_safari_find_match_word_starts_only }}"
      type: bool

- name: Remove useless icons from Safari’s bookmarks bar
  state:
    defaults:
      key: com.apple.Safari:ProxiesInBookmarksBar
      set: []
  when: osx_safari_remove_useless_bookmark_icons

- name: Enable the Develop menu and the Web Inspector in Safari
  state:
    defaults:
    - key: com.apple.Safari:IncludeDevelopMenu
      set: "{{ osx_safari_dev_and_inspector_menus }}"
      type: bool
    - key: com.apple.Safari:WebKitDeveloperExtrasEnabledPreferenceKey
      set: "{{ osx_safari_dev_and_inspector_menus }}"
      type: bool
    - key: com.apple.Safari:com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
      set: "{{ osx_safari_dev_and_inspector_menus }}"
      type: bool
  when: osx_safari_dev_and_inspector_menus is defined

- name: Add a context menu item for showing the Web Inspector in web views
  state:
    defaults:
      key: NSGlobalDomain:WebKitDeveloperExtras
      set: "{{ osx_safari_inspector_context_menu }}"
      type: bool
  when: osx_safari_inspector_context_menu is defined
