---
###############################################################################
# Safari & WebKit                                                             #
###############################################################################

# i don't really use safari...

# # Privacy: don’t send search queries to Apple
# defaults write com.apple.Safari UniversalSearchEnabled -bool false
# defaults write com.apple.Safari SuppressSearchSuggestions -bool true

# # Press Tab to highlight each item on a web page
# defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
# defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

- name: Show the full URL in the address bar
  # note: this still hides the scheme
  state:
    defaults:
      key: com.apple.Safari:ShowFullURLInSmartSearchField
      set: "{{ osx_safari_full_url_in_addr_bar|bool }}"
  when: osx_safari_full_url_in_addr_bar is defined

- name: Set Safari’s home page to `about:blank` for faster loading
  state:
    defaults:
      key: com.apple.Safari:HomePage
      set: "{{ osx_safari_home_page }}"
  when: osx_safari_home_page is defined

- name: Prevent Safari from opening 'safe' files automatically after downloading
  state:
    defaults:
      key: com.apple.Safari:AutoOpenSafeDownloads
      set: "{{ osx_safari_auto_open_safe_files|bool }}"
  when: osx_safari_auto_open_safe_files is defined

- name: Disable hitting the Backspace key to go to the previous page in history
  # (i don't like backspace-as-back)
  state:
    defaults:
      key: com.apple.Safari:com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled
      set: "{{ osx_safari_backspace_back|bool }}"
  when: osx_safari_backspace_back is defined

- name: Hide Safari’s bookmarks bar by default
  state:
    defaults:
      key: com.apple.Safari:ShowFavoritesBar
      set: "{{ osx_safari_show_favs_bar|bool }}"
  when: osx_safari_show_favs_bar is defined

# # Hide Safari’s sidebar in Top Sites
# defaults write com.apple.Safari ShowSidebarInTopSites -bool false

- name: Disable Safari’s thumbnail cache for History and Top Sites
  state:
    defaults:
      key: com.apple.Safari:DebugSnapshotsUpdatePolicy
      set: 2
  when: osx_safari_disable_hist_top_sites_thumbs

- name: Enable Safari’s debug menu
  state:
    defaults:
      key: com.apple.Safari:IncludeInternalDebugMenu
      set: "{{ osx_safari_enable_debug_menu|bool }}"
  when: osx_safari_enable_debug_menu is defined

# # Make Safari’s search banners default to Contains instead of Starts With
# defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

- name: Remove useless icons from Safari’s bookmarks bar
  state:
    defaults:
      key: com.apple.Safari:ProxiesInBookmarksBar
      set: []
  when: osx_safari_remove_useless_bookmark_icons

- name: Enable the Develop menu and the Web Inspector in Safari
  state:
    defaults:
    - key: com.apple.Safari:IncludeDevelopMenu
      set: "{{ osx_safari_dev_and_inspector_menus|bool }}"
    - key: com.apple.Safari:WebKitDeveloperExtrasEnabledPreferenceKey
      set: "{{ osx_safari_dev_and_inspector_menus|bool }}"
    - key: com.apple.Safari:com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
      set: "{{ osx_safari_dev_and_inspector_menus|bool }}"
  when: osx_safari_dev_and_inspector_menus is defined

- name: Add a context menu item for showing the Web Inspector in web views
  state:
    defaults:
      key: NSGlobalDomain:WebKitDeveloperExtras
      set: "{{ osx_safari_inspector_context_menu|bool }}"
  when: osx_safari_inspector_context_menu is defined
