---
###############################################################################
# Time Machine                                                                #
###############################################################################

- name: >
    Prevent Time Machine from prompting to use new hard drives as
    backup volume

  state:
    defaults:
      key: com.apple.TimeMachine:DoNotOfferNewDisksForBackup
      set: "{{ not osx_time_machine_prompt_on_new_drives }}"
  when: osx_time_machine_prompt_on_new_drives is defined

- name: Disable local Time Machine snapshots
  # this is what was there?
  #
  # hash tmutil &> /dev/null && sudo tmutil disablelocal
  #
  sudo: true
  state:
    time_machine:
      key: local_backups
      set: "{{ osx_time_machine_local_backups }}"
  when: osx_time_machine_local_backups is defined