---
# handlers file for nrser.osx

# the list from .osx:
# for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
# 	"Dock" "Finder" "Google Chrome" "Google Chrome Canary" "Mail" "Messages" \
# 	"Opera" "Safari" "SizeUp" "Spectacle" "SystemUIServer" "Terminal" \
# 	"Transmission" "Twitter" "iCal"; do
# 	killall "${app}" > /dev/null 2>&1
# done

- name: restart SystemUIServer
  shell: killall SystemUIServer

- name: restart Finder
  shell: killall Finder

- name: require logout/login
  debug:
    msg: "NOTICE: logout/login required to see changes"

- name: require restart
  debug:
    msg: "NOTICE: requires restart to see changes"

- name: restart Dock
  shell: killall Dock

# spotlight

# Load new settings before rebuilding the index
# killall mds > /dev/null 2>&1
- name: restart mds (metadata server)
  command: killall mds

# Make sure indexing is enabled for the main volume
# sudo mdutil -i on / > /dev/null

# Rebuild the index from scratch
# sudo mdutil -E / > /dev/null
- name: rebuild spotlight index
  sudo: true
  command: mdutil -E /
